#!/bin/bash

DNSNAME=(tuimac docker-host1)
IPADDR=(10.0.0.1 10.3.4.4)
NAME=""
IP=""

function sendRequest(){
    sleep 0.5
    nslookup $NAME localhost
}

function sendInverseRequest(){
    sleep 0.5
    nslookup $IP localhost
}

for NAME in "${DNSNAME[@]}"; do
    sendRequest &
done
for IP in "${IPADDR[@]}"; do
    sendInverseRequest &
done
sudo src/main.py
