#!/bin/bash

function usage(){
    echo "Usage: "${0}" <create> | <delete>"
    exit 1
}

function main(){
    [[ -z $1 ]] && { usage; }
    if [ $1 == "create" ]; then
        docker-compose up -d
        sleep 15
        cat jenkins/tagdns-config.xml | java -jar jenkins/jenkins-cli.jar -s http://node-master:8000 create-job tagdns
    elif [ $1 == "delete" ]; then
        docker stop jenkins
        docker rm jenkins
        docker rmi jenkins/jenkins:latest
        docker rmi docker_jenkins:latest
    else
        usage
    fi
}

main $1
