version: '3'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8000:8080"
      - "50000:50000"
    volumes:
      - "./jenkins/volume:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
    tty: true
    stdin_open: true

networks:
  default:
    external:
      name: br0
