pipeline {
    agent any
    environment {
        NAME = "tagdns_test"
        REPOSITORY = "https://github.com/tuimac/tagdns.git"
        DEPLOY = "/root/deploy"
        DOCKERFILE = "/root/deploy/tagdns/docker"
        TESTDIR="/opt/tagdns"
    }
    stages("Tagdns Pipeline") {
        stage("Clone tagdns project") {
            steps {
                dir("${DEPLOY}") {
                    sh "rm -rf tagdns"
                    sh "git clone ${REPOSITORY}"
                }
            }
        }
        stage("Build Image") {
            steps {
                dir("${DOCKERFILE}") {
                    sh "docker build -t ${NAME} ."
                }
            }
            post {
                failure {
                    sh "docker image prune -f"
                    echo "Failed to build image!"
                }
            }
        }
        stage("Start Container") {
            steps {
                sh "docker run -itd --name ${NAME} \
                                    -h ${NAME} \
                                    -v /etc/localtime:/etc/localtime:ro \
                                    -v volume:/tmp \
                                    -p 5353:53 \
                                    --network=bridge \
                                    ${NAME}"
            }
            post {
                failure {
                    sh "docker stop ${NAME}"
                    sh "docker rm ${NAME}"
                    sh "docker rmi ${NAME}"
                    sh "docker container prune -f"
                    sh "docker image prune -f"
                    echo "Failed to start container!"
                }
            }
        }
        stage("Network Test") {
            steps {
                dir("${TESTDIR}") {
                    sh "python3 main_test.py"
                }
            }
            post {
                failure {
                    echo "Network Test has been failed...!"
                }
            }
        }
    }
    post {
        cleanup {
            sh "docker stop ${NAME}"
            sh "docker rm ${NAME}"
            sh "docker rmi ${NAME}"
            sh "docker container prune -f"
            sh "docker image prune -f"
        }
        success {
            echo "No problem!!"
        }
        failure {
            echo "Failed to delete!"
        }
    }
}
